version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats:
   - pdf

# Conda environment
conda:
  environment: environment.yml