version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats:
   - pdf

# Conda environment
conda:
  environment: environment.yml