

###############
# Integration #
###############

[integration]
name = "gbm_proteomics"
# Correlation methods: spearman, pearson
corr_method = "pearson"
# highest k-values will be eliminated until median correlation is below this value
max_median_corr = 0
# Quantile from the negative half of the correlation distribution from which to derive the correlation threshold.
# Lower values result in more edges, higher values result in fewer edges.
negative_corr_quantile = 0.95

[sns]
layout_algorithm = "spring"  # Options include neato, spring, umap
node_size = 30
plot_size = [10, 10]

################################
# Datasets and Sample Metadata #
################################

# Specify a dataset name (eg. CPTAC) to be used for this dataset in plots
[datasets.CPTAC]
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/cnmf_results/cptac_gbm_1_kl/cptac_gbm_1_kl.h5ad"
color = "royalblue"

# You can specify k-values to include, separately for each dataset, or use the default.
# selected_k = [2, 3, 4, 5]             # k-values can be specified as a list of integers

[datasets.UCC]
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/cnmf_results/gbm_ffpe_proteogenomics_1_kl/gbm_ffpe_proteogenomics_1_kl.h5ad"
color = "gold"

[datasets.Yonsei]
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/cnmf_results/yonsei_1_kl/yonsei_1_kl.h5ad"
color = "tomato"

[datasets.Diamandis]
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/cnmf_results/diamandis_nobulk_1_kl/diamandis_nobulk_1_kl.h5ad"
color = "lightgreen"


##########################
# Metadata Color Schemes #
##########################

# The `#` sign is a comment in TOML, so make sure you quote hex-formatted colors

[metadata_colors]
missing_data = "#dddddd"

[metadata_colors.detailed_category]
"N" = "#b0e0e6"
"N.untx" = "#e0ffff"
"N.Cx" = "#0000e0"
"N.Wm" = "#00ffff"
"BrMet.Lu" = "#40356b"
"BrMet.Me" = "#594e4f"
"BrMet.Br" = "#000000"
"BrMet.Ov" = "#2f4f4f"
"Spl" = "#f4e2b5"
"P" = "#00c000"
"P.Core" = "#006400"
"P.Enh" = "#d2fd32"
"P.Edge" = "#90ee90"
"R" = "#e00000"
"R.Core" = "#8b0000"
"R.Enh" = "#ffa500"
"R.Edge" = "#f08080"
"R.2" = "#ff0000"
"LE" = "#b0e0e6"
"CT" = "#006400"
"MVP" = "#ffff00"
"IT" = "#90ee90"
"PAN" = "#808000"
"whole" = "#00c000"

[metadata_colors.simple_category]
"N.Cx" = "#0000e0"
"N.Wm" = "#00ffff"
"P" = "#00c000"
"R" = "#e00000"
"BrMet" = "#594e2e"
"Spl" = "#f4e2b5"
"LE" = "#b0e0e6"
"CT" = "#006400"
"MVP" = "#ffff00"
"IT" = "#90ee90"
"PAN" = "#808000"

[metadata_colors.multiomic]
"nmf1" = "#c25e84"
"nmf2" = "#c89e28"
"nmf3" = "#67adde"
"IDH mutant" = "#508a5a"

[metadata_colors.r_wang_cancer_cell_2017]
"Proneural" = "#c25e84"
"Classical" = "#67adde"
"Mesenchymal" = "#c89e28"
"IDH mutant" = "#508a5a"

[metadata_colors.d_methyl]
"dm1" = "#d76f90"
"dm2" = "#b99622"
"dm3" = "#75b52d"
"dm4" = "#68bda6"
"dm5" = "#63a0f9"
"dm6" = "#c66bf6"

[metadata_colors.d_methyl_mnp]
"A IDH" = "#d4b527"
"A IDH, HG" = "#c9c22b"
"GBM, MES" = "#53752b"
"GBM, RTK I" = "#7bbb2f"
"GBM, RTK II" = "#9cf867"
"GBM, RTK III" = "#91e039"
"GBM, MID" = "#3b6616"

[metadata_colors.is_gcimp]
true = "#310042"
false = "#ede03c"

[metadata_colors.immune]
"im1" = "#66122a"
"im2" = "#a94a1c"
"im3" = "#e4c763"
"im4" = "#68589f"

[metadata_colors.mir]
"mi1" = "#d76f90"
"mi2" = "#ad9e21"
"mi3" = "#63bc60"
"mi4" = "#66b2e3"
"mi5" = "#b774f8"

