# Provide a name for the integration

name = "GBM Proteomics"


################################
# Datasets and Sample Metadata #
################################

[[datasets]]
alias = "CPTAC"
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/cNMF/output/cptac_gbm_imputed_odg1_kl.h5mu"
color = "royalblue"
metadata = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/sample_metadata/cnmfsns_metadata/cptac_gbm.metadata.txt"

[[datasets]]
alias = "UCC"
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/cNMF/output/gbm_ffpe_proteogenomics_imputed_odg1_kl.h5mu"
color = "gold"
metadata = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/sample_metadata/cnmfsns_metadata/gbm_ffpe_proteogenomics.metadata.txt"

[[datasets]]
alias = "Yonsei"
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/cNMF/output/yonsei_imputed_odg1_kl.h5mu"
color = "tomato"
metadata = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/sample_metadata/cnmfsns_metadata/yonsei.metadata.txt"

[[datasets]]
alias = "Diamandis"
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/cNMF/output/diamandis_imputed_odg1_kl.h5mu"
color = "lightgreen"
metadata = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/sample_metadata/cnmfsns_metadata/diamandis.metadata.txt"


##########################
# Metadata Color Schemes #
##########################

[metadata_colors.detailed_category]
"N" = "#b0e0e6"
"N.untx" = "#e0ffff"
"N.Cx" = "#0000e0"
"N.Wm" = "#00ffff"
"BrMet.Lu" = "#40356b"
"BrMet.Me" = "#594e4f"
"BrMet.Br" = "#000000"
"BrMet.Ov" = "#2f4f4f"
"Spl" = "#f4e2b5"
"P" = "#00c000"
"P.Core" = "#006400"
"P.Enh" = "#d2fd32"
"P.Edge" = "#90ee90"
"R" = "#e00000"
"R.Core" = "#8b0000"
"R.Enh" = "#ffa500"
"R.Edge" = "#f08080"
"R.2" = "#ff0000"
"LE" = "#b0e0e6"
"CT" = "#006400"
"MVP" = "#ffff00"
"IT" = "#90ee90"
"PAN" = "#808000"
"whole" = "#00c000"

[metadata_colors.simple_category]
"N.Cx" = "#0000e0"
"N.Wm" = "#00ffff"
"P" = "#00c000"
"R" = "#e00000"
"BrMet" = "#594e2e"
"Spl" = "#f4e2b5"
"LE" = "#b0e0e6"
"CT" = "#006400"
"MVP" = "#ffff00"
"IT" = "#90ee90"
"PAN" = "#808000"
"Other" = "#dddddd"

[metadata_colors.multiomic]
"nmf1" = "#c25e84"
"nmf2" = "#c89e28"
"nmf3" = "#67adde"
"IDH mutant" = "#508a5a"
"Other" = "#dddddd"

[metadata_colors.r_wang_cancer_cell_2017]
"Proneural" = "#c25e84"
"Classical" = "#67adde"
"Mesenchymal" = "#c89e28"
"IDH mutant" = "#508a5a"
"Other" = "#dddddd"

[metadata_colors.d_methyl]
"dm1" = "#d76f90"
"dm2" = "#b99622"
"dm3" = "#75b52d"
"dm4" = "#68bda6"
"dm5" = "#63a0f9"
"dm6" = "#c66bf6"
"Other" = "#dddddd"

[metadata_colors.d_methyl_mnp]
"A IDH" = "#d4b527"
"A IDH, HG" = "#c9c22b"
"GBM, MES" = "#53752b"
"GBM, RTK I" = "#7bbb2f"
"GBM, RTK II" = "#9cf867"
"GBM, RTK III" = "#91e039"
"GBM, MID" = "#3b6616"
"Other" = "#dddddd"

[metadata_colors.is_gcimp]
true = "#310042"
false = "#ede03c"
"Other" = "#dddddd"

[metadata_colors.immune]
"im1" = "#66122a"
"im2" = "#a94a1c"
"im3" = "#e4c763"
"im4" = "#68589f"
"Other" = "#dddddd"

[metadata_colors.mir]
"mi1" = "#d76f90"
"mi2" = "#ad9e21"
"mi3" = "#63bc60"
"mi4" = "#66b2e3"
"mi5" = "#b774f8"
"Other" = "#dddddd"

