# Provide a name for the integration
[integration]
name = "Test integration"


################################
# Datasets and Sample Metadata #
################################

[datasets.UCC]
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/cNMF-SNS/cnmf_results/gbm_ffpe_proteogenomics_1_kl/gbm_ffpe_proteogenomics_1_kl.h5ad"
color = "gold"

[datasets.Yonsei]
filename = "/mnt/c/Users/verhe/MorrissyLab Dropbox/Proteomics/tmt_proteomics/cNMF-SNS/cnmf_results/yonsei_1_kl/yonsei_1_kl.h5ad"

##########################
# Metadata Color Schemes #
##########################

[metadata_colors]
missing_data = "#dddddd"

[metadata_colors.detailed_category]
"N" = "#b0e0e6"
"P" = "#00c000"
"R" = "#e00000"

[metadata_colors.simple_category]
"N.Cx" = "#0000e0"
"P" = "#00c000"
"R" = "#e00000"
"CT" = "#006400"
"MVP" = "#ffff00"
"IT" = "#90ee90"